routes/web.php
<?php

use App\Http\Controllers\StudentController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/students','StudentController');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('student.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return "this is store";

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    {{-- bootstrap --}}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {{-- //script with jquery and ajax --}}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{{-- Font Awesome  --}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/student/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

@include('student.form')

</div>
@endsection

resources/views/student/form.blade.php
<div class="row">
    <div class="col-md-6">
        {{Form::open(['route' => "students.store", 'method' => 'POST'])}}

        <div class="row">
            <div class="col-md-6">
                {{Form::label( 'name','Enter your name : ',['title' => 'name', 'style' => "color:black"])}}
                {{-- first value is "for" and second value is "value" --}}
            </div>

            <div class="col-md-6">
                {{Form::text('name', '',['title'=>'name here', 'class' => " mb-3", 'id' => 'myname'])

                }}
                {{-- first value is "name" second value is "value" --}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {{Form::label('Password : ')}}
            </div>
            <div class="col-md-6">
                {{-- {{Form::password('password',['class'=>'form-control mb-3', 'aria-label' => "Amount (to the nearest dollar)"])}} --}}
                <div class="input-group">
                    <input id="hide" type="password" class="form-control mb-3" aria-label="Amount (to the nearest dollar)" />
                    <div class="input-group-append">
                        <span id="showpass" class="input-group-text mb-3" style="cursor: pointer"><i class="fa fa-eye" ></i></span>
                    </div>
                </div>
                
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {{Form::label('email', 'Email : ')}}
            </div>
            <div class="col-md-6">
                {{Form::email('email','', ['class' => ' mb-3'])}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-5">
                {{Form::label('Hobby : ')}}
            </div>
            <div class="col-md-7">
                {{Form::label('Cricket')}}
                {{Form::checkbox('hobby', 'cricket')}}
                {{Form::label('Badminton')}}
                {{Form::checkbox('hobby', 'badminton')}}
                {{Form::label('Football')}}
                {{Form::checkbox('hobby', 'football')}}<br />
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="row">
            <div class="col-md-6">
                {{Form::label('Gender : ')}}
            </div>
            <div class="col-md-6">
                {{Form::label('Male')}}
                {{Form::radio('gender', 'male')}}
                {{Form::label('Female')}}
                {{Form::radio('gender', 'female')}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {{Form::label('Enrollment No. : ')}}
            </div>
            <div class="col-md-6">
                {{Form::number('enrollno', '', ['class' => ' mb-3'])}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {{Form::label('Date : ')}}
            </div>
            <div class="col-md-6">
                {{Form::date('date','', ['class' => ' mb-3'])}}
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                {{Form::label('Subjects')}}
            </div>
            <div class="col-md-6">
                {{Form::select('subject',['maths' => 'Maths', 'science'=> "Science", 'physics' =>
                'Physics'],'',['placeholder' => 'Select any one', 'class' => 'form-control mb-3'])}}
            </div>
        </div>
    </div>
</div>


{{Form::submit('Click me',['class'=>'btn btn-primary btn-sm'])}}
{{Form::close()}}


<script>

$(function(){

    $('#showpass').on('click', function(){

        if($('#hide').attr('type') == 'text'){
            $('#hide').attr('type', 'password');
        }else{
        $('#hide').attr('type', 'text');
        }

        setTimeout(() => {
            $('#hide').attr('type', 'password');
        }, 2000);

    })


})

</script>

resources/views/student/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

   <a href="{{route('students.create')}}"> <button class="btn btn-success btn-sm">Add student</button></a>

</div>


@endsection